version: 0.0.1
name: fm_v2
services:
    api:
        build:
            context: .
            dockerfile: ./deployments/Dockerfile
            target: base
        container_name: fm_v2
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - APP_PORT=$APP_PORT
        ports:
            - "8888:${APP_PORT}"
        env_file:
            - .env
    mongodb:
      image: mongo:latest
      env_file:
        - .env
      environment:
        - DB_PORT=$DB_PORT
      ports:
        - "27017:${DB_PORT}"